---
language: python
python: "2.7"

# Use the new container infrastructure
sudo:
  - required
services:
  - docker
# Install ansible
addons:
  apt:
    packages:
      - python-pip

before_install:
  - sudo apt-get update

install:
  # Install ansible
  - pip install ansible
  # Install python interface to docker
  - pip install docker
  # Install molecule
  - pip install molecule
  # Check ansible version
  - ansible --version

script:
  - molecule dependency
  - molecule syntax
  - molecule create
  - molecule converge
  - molecule idempotence
  - molecule lint
  - molecule verify
  - molecule destroy

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    rooms:
      - africa-arabia-roc:RtLMfiuARuPNXMNIXn5RVTkF#code
