---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: true
dist: trusty
services: docker
# Install ansible
addons:
  apt:
    packages:
      - python-pip

before_install:
  - sudo apt-get update

install:
  # Install ansible
  - pip install ansible
  - pip install molecule
  # Check ansible version
  - ansible --version

script:
  # Basic role syntax check
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    rooms:
      - africa-arabia-roc:RtLMfiuARuPNXMNIXn5RVTkF#code
