---
- name: copy over the local config files
  copy:
    src: "etc/cvmfs/{{ item }}"
    dest: "/etc/cvmfs/{{ item }}"
  with_items:
    - default.local
    - keys/apprepo.sagrid.ac.za.pub
    - config.d/apprepo.sagrid.ac.za.conf
    - keys/devrepo.sagrid.ac.za.pub
    - config.d/devrepo.sagrid.ac.za.conf
    - keys/fastrepo.sagrid.ac.za.pub
    - config.d/fastrepo.sagrid.ac.za.conf
  tags:
    - cvmfs
    - config

- name: ensure that the CVMFS mount point is available
  file:
    path: /cvmfs
    state: directory
    mode: a+rwx

- name: mount the repo
  mount:
    name: /cvmfs/fastrepo.sagrid.ac.za
    fstype: cvmfs
    state: present
    src: fastrepo.sagrid.ac.za



- name: check that the repo is mounted
  stat: "path=/cvmfs/{{ item }}"
  with_items: "{{ repos }}"
  register: p
  failed_when: "p.stat.exists == false"

- name: debug some stuff
  debug:
    var: p.results
  #when: p.stat.isdir is defined and p.stat.isdir
