---
- name: Copy CODE-RADE configs
  copy:
    src: "etc/cvmfs/domain.d/code-rade.africa-grid.org.conf"
    dest: "/etc/cvmfs/domain.d/code-rade.africa-grid.org.conf"
  tags:
    - cvmfs
    - config

- name: Ensure that keys dir is present
  file:
    path: "/etc/cvmfs/keys/africa-grid.org/"
    state: directory

- name: Copy CODE-RADE keys
  copy:
    src: "etc/cvmfs/keys/africa-grid.org/code-rade.africa-grid.org.pub"
    dest: "/etc/cvmfs/keys/africa-grid.org/code-rade.africa-grid.org.pub"

- name: Copy Default config
  copy:
    src: "etc/cvmfs/default.local"
    dest: "/etc/cvmfs/default.local"

- name: add the CVMFS master
  copy:
    src: etc/auto.master
    dest: /etc/auto.master
    mode: u=rw,g=r,o=r

- name: mount the repo
  mount:
    name: "{{ mount_dir}}/{{ item }}"
    fstype: cvmfs
    state: mounted
    src: "{{ item }}"
  with_items: "{{repos}}"
  register: mount_state
  failed_when: false

- debug:
    var: mount_state
