---
- name: Copy CODE-RADE configs
  copy:
    src: "etc/cvmfs/domain.d/code-rade.africa-grid.org.conf"
    dest: "/etc/cvmfs/domain.d/code-rade.africa-grid.org.conf"
  tags:
    - cvmfs
    - config

- name: Ensure that keys dir is present
  file:
    path: "etc/cvmfs/keys/africa-grid.org/"
    state: directory
- name: Copy CODE-RADE keys
  copy:
    src: "etc/cvmfs/keys/africa-grid.org/code-rade.africa-grid.org.pub"
    dest: "/etc/cvmfs/keys/africa-grid.org/code-rade.africa-grid.org.pub"

- name: add the CVMFS master
  copy:
    src: etc/auto.master
    dest: /etc/auto.master
    mode: u=rw,g=r,o=r


- name: restart autofs
  service:
    name: autofs
    state: restarted
  when: ansible_virtualization_type != 'docker'
  tags:
    - cvmfs

- name: check that the repo is mounted
  stat: "path=/cvmfs/{{ item }}"
  with_items: "{{ repos }}"
  register: p
  failed_when: "p.stat.exists == false"
  retries: 3
  delay: 3

- name: debug some stuff
  debug:
    var: p
  #when: p.stat.isdir is defined and p.stat.isdir
