---
- name: copy over the local config files
  copy:
    src: "etc/cvmfs/{{ item }}"
    dest: "/etc/cvmfs/{{ item }}"
  with_items:
    - default.local
    - keys/apprepo.sagrid.ac.za.pub
    - config.d/apprepo.sagrid.ac.za.conf
    - keys/devrepo.sagrid.ac.za.pub
    - config.d/devrepo.sagrid.ac.za.conf
    - keys/fastrepo.sagrid.ac.za.pub
    - config.d/fastrepo.sagrid.ac.za.conf
  tags:
    - cvmfs
    - config

- name: add the CVMFS master
  copy:
    src: etc/auto.master
    dest: /etc/auto.master
    mode: u=rw,g=r,o=r


- name: restart autofs
  service:
    name: autofs
    state: restarted
  when: ansible_virtualization_type != 'docker'
  tags:
    - cvmfs

- name: check that the repo is mounted
  stat: "path=/cvmfs/{{ item }}"
  with_items: "{{ repos }}"
  register: p
  failed_when: "p.stat.exists == false"

- name: debug some stuff
  debug:
    var: p
  #when: p.stat.isdir is defined and p.stat.isdir
