---
- name: Install package (Debian)
  apt:
    deb: https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
    state: present

- name: ensure that cvmfs user is present
  user:
    name: cvmfs
    state: present
  become: true

- name: Do we even need CVMFS ?
  stat:
    path: /usr/bin/cvmfs2
  register: cvmfs_present

- name: cvmfs stat
  debug:
    msg: "{{ cvmfs_present.stat }}"

- name: Install prerequisites
  apt:
    name: "{{ item }}"
    state: present
  with_items: prerequisites
  become: true
  when: cvmfs_present.stat.exists == false
